Update patch set 3
Patch Set 3:

lock_after_timeout_entries: "???" means "Right now" but it's supposed to mean "Immediately" which is translated to "??".

turn_on_radio & turn_off_radio: A string like "Turn on (or off) blah-blah" is supposed to be translate like "blah-blah?OFF???" but it's missing a "???" part.

crypt_keeper_encrypt_summary & crypt_keeper_encrypt_summary:  I've never seen "?????" in other parts of AOSP. I'm suggest better translations.

wifi_empty_list_wifi_off: Revert my previous change and add a missing comma which exists in the original string.

brightness: "??????" means "Screen brightness" but it's supposed to mean "Brightness" which is translated to "???".

screensaver_settings_disabled_prompt: Add a missing comma which exists in the original string.

usb_tethering_available_subtext: Improve a translation.

From bluetooth_tethering_available_subtext to bluetooth_tethering_devices_connected_subtext: "??" means "Share" but it's supposed to mean "Sharing" which is translated to "???????".

bluetooth_tethering_off_subtext and bluetooth_tethering_off_subtext: "?????" means "Don't share" but it's supposed to mean "Not sharing" which is translated to "????????".

bluetooth_tethering_overflow_error: When we count the number of devices, we're supposed to add "?" after the number like "4?" (4 devices) but "?" is used here.

lockpattern_settings_enable_visible_pattern_title and lockpattern_settings_enable_power_button_instantly_locks: "??" is supposed to be omitted in a title string.

strict_mode: They sometimes translate "Enable" to "??", other times "???", and still other times "?????". They should be unified to "???" I think.

disable_overlays: They sometimes translate "Disable" to "??", other times "???", and still other times "?????". They should be unified to "???" I think.

From data_usage_menu_restrict_background to data_usage_app_restrict_background: "??" is supposed to be omitted in a title string.

Patch-set: 3