Fix com.android.phone crash because of deadlock
It is temporary [BUGBASH-1609] fix: just catch an exception and move on.

Crash details:
 Process: com.android.phone, PID: 5149
 java.lang.RuntimeException: Unable to resume activity {com.android.settings/com.android.settings.RadioInfo}: java.lang.RuntimeException: This method will deadlock if called from the main thread.
 Caused by: java.lang.RuntimeException: This method will deadlock if called from the main thread.
    at org.codeaurora.ims.ImsConfigImpl.sendRequest(ImsConfigImpl.java:285)
    at org.codeaurora.ims.ImsConfigImpl.getProvisionedValue(ImsConfigImpl.java:145)
    at com.android.ims.ImsConfig.getProvisionedValue(ImsConfig.java:560)
    at com.android.settings.RadioInfo.isFeatureProvisioned(RadioInfo.java:1279)
    at com.android.settings.RadioInfo.isEabProvisioned(RadioInfo.java:1262)
    at com.android.settings.RadioInfo.updateImsProvisionedState(RadioInfo.java:1326)
    at com.android.settings.RadioInfo.onResume(RadioInfo.java:465)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
    at android.app.Activity.performResume(Activity.java:7117)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
    ... 10 more
 Process com.android.phone has crashed too many times: killing!
 Force finishing activity com.android.settings/.RadioInfo

Change-Id: I04d10ccafadf0e3e72dd60a45fddf2f9e100bf65