Update patch set 3
Patch Set 3:

> girls maybe give steve some logs. would be much easyer than
 > complaining....

You mention girls give some logs ... Maybe that was the reason not to send a log, lol, and by the way it was not a complain, it was my experience.
Nevertheless here is the log:
java.lang.IllegalArgumentException: Invalid value: 0:0,000000|0,000000|0,000000|0,491400|0,000000 for setting: display_picture_adjustment
	at android.os.Parcel.readException(Parcel.java:1624)
	at android.os.Parcel.readException(Parcel.java:1573)
	at cyanogenmod.hardware.ILiveDisplayService$Stub$Proxy.setPictureAdjustment(ILiveDisplayService.java:744)
	at cyanogenmod.hardware.LiveDisplayManager.setPictureAdjustment(LiveDisplayManager.java:465)
	at com.android.settings.livedisplay.PictureAdjustment.updateAdjustment(PictureAdjustment.java:209)
	at com.android.settings.livedisplay.PictureAdjustment.-wrap0(PictureAdjustment.java)
	at com.android.settings.livedisplay.PictureAdjustment$ColorSeekBar.onProgressChanged(PictureAdjustment.java:235)
	at android.widget.SeekBar.onProgressRefresh(SeekBar.java:93)
	at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:1303)
	at android.widget.ProgressBar.refreshProgress(ProgressBar.java:1315)
	at android.widget.ProgressBar.setProgress(ProgressBar.java:1361)
	at android.widget.AbsSeekBar.trackTouchEvent(AbsSeekBar.java:666)
	at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:610)
	at android.view.View.dispatchTouchEvent(View.java:9301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2659)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1787)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:787)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2620)
	at android.view.View.dispatchPointerEvent(View.java:9521)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4104)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3795)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3852)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5932)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5906)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5867)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6035)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Patch-set: 3